# SPDX-FileCopyrightText: 2026 Alok Kumar Mishra <alok16022006@gmail.com>
# SPDX-License-Identifier: LGPL-3.0-only

# Cross-file for building rizin for Android x86_64.

[binaries]
c       = '${ANDROID_NDK_LATEST_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android33-clang'
cpp     = '${ANDROID_NDK_LATEST_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android33-clang++'
ar      = '${ANDROID_NDK_LATEST_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar'
as      = '${ANDROID_NDK_LATEST_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android-as'
ranlib  = '${ANDROID_NDK_LATEST_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android-ranlib'
ld      = '${ANDROID_NDK_LATEST_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android-ld'
strip   = '${ANDROID_NDK_LATEST_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android-strip'
pkg-config = 'false'

[properties]
sys_root = '${ANDROID_NDK_LATEST_HOME}/sysroot'

[built-in options]
c_link_args = ['-lm','-ldl']

[host_machine]
system = 'android'
cpu_family = 'x86'
cpu = 'x86_64'
endian = 'little'
