# SPDX-FileCopyrightText: 2026 Alok Kumar Mishra <alok16022006@gmail.com>
# SPDX-License-Identifier: LGPL-3.0-only

# Cross-file for building the rz-frida rizin plugin for Android arm (armv7a).

[binaries]
c       = '${ANDROID_NDK_LATEST_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi33-clang'
cpp     = '${ANDROID_NDK_LATEST_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi33-clang++'
ar      = '${ANDROID_NDK_LATEST_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar'
ranlib  = '${ANDROID_NDK_LATEST_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib'
strip   = '${ANDROID_NDK_LATEST_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-strip'
pkgconfig = 'pkg-config'

[properties]
pkg_config_libdir = ['${ANDROID_STAGING}/lib/pkgconfig']

[host_machine]
system = 'android'
cpu_family = 'arm'
cpu = 'arm'
endian = 'little'
