// SPDX-FileCopyrightText: 2021-2026 RizinOrg <info@rizin.re>
// SPDX-License-Identifier: LGPL-3.0-only
//
// WARNING: This file was auto-generated by cmd_descs_generate.py script. Do not
// modify it manually. Look at cmd_descs.yaml if you want to update commands.
//

#include <rz_cmd.h>
#include <rz_core.h>
#include <rz_util.h>

// Command handlers, manually defined somewhere else
// "Frs"
RZ_IPI RzCmdStatus rz_cmd_fridas_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "Fru"
RZ_IPI RzCmdStatus rz_cmd_fridau_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "Frd"
RZ_IPI RzCmdStatus rz_cmd_fridad_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "Frp"
RZ_IPI RzCmdStatus rz_cmd_fridap_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "Fra"
RZ_IPI RzCmdStatus rz_cmd_fridaa_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "Fro"
RZ_IPI RzCmdStatus rz_cmd_fridao_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "Frr"
RZ_IPI RzCmdStatus rz_cmd_fridar_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "Frc"
RZ_IPI RzCmdStatus rz_cmd_fridac_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "Fre"
RZ_IPI RzCmdStatus rz_cmd_fridae_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "Frl"
RZ_IPI RzCmdStatus rz_cmd_fridal_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "Fri"
RZ_IPI RzCmdStatus rz_cmd_fridai_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "Frm"
RZ_IPI RzCmdStatus rz_cmd_fridam_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "Frx"
RZ_IPI RzCmdStatus rz_cmd_fridax_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "Frw"
RZ_IPI RzCmdStatus rz_cmd_fridaw_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "FrR"
RZ_IPI RzCmdStatus rz_cmd_fridaR_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "Frt"
RZ_IPI RzCmdStatus rz_cmd_fridat_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "FrM"
RZ_IPI RzCmdStatus rz_cmd_fridaM_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "FrE"
RZ_IPI RzCmdStatus rz_cmd_fridaE_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "FrI"
RZ_IPI RzCmdStatus rz_cmd_fridaI_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "FrS"
RZ_IPI RzCmdStatus rz_cmd_fridaS_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "Frb"
RZ_IPI RzCmdStatus rz_cmd_fridab_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "Frb-"
RZ_IPI RzCmdStatus rz_cmd_fridab_minus_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "Frg"
RZ_IPI RzCmdStatus rz_cmd_fridag_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "FrB"
RZ_IPI RzCmdStatus rz_cmd_fridaB_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "FrW"
RZ_IPI RzCmdStatus rz_cmd_fridaW_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "FrW-"
RZ_IPI RzCmdStatus rz_cmd_fridaW_minus_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "FrJ"
RZ_IPI RzCmdStatus rz_cmd_fridaJ_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "FrL"
RZ_IPI RzCmdStatus rz_cmd_fridaL_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "FrC"
RZ_IPI RzCmdStatus rz_cmd_fridaC_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "FrN"
RZ_IPI RzCmdStatus rz_cmd_fridaN_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "FrRN"
RZ_IPI RzCmdStatus rz_cmd_fridaRN_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "Frf"
RZ_IPI RzCmdStatus rz_cmd_fridaf_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "FrX"
RZ_IPI RzCmdStatus rz_cmd_fridaX_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "FrD"
RZ_IPI RzCmdStatus rz_cmd_fridaD_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
RZ_IPI char **rz_frida_autocomplete_class(RzCore *core);
// "FrIm"
RZ_IPI RzCmdStatus rz_cmd_fridaIm_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);

// Main function that initialize the entire commands tree
RZ_IPI void rzshell_cmddescs_init(RzCore *core);
