// SPDX-FileCopyrightText: 2021-2026 RizinOrg <info@rizin.re>
// SPDX-License-Identifier: LGPL-3.0-only
//
// WARNING: This file was auto-generated by cmd_descs_generate.py script. Do not
// modify it manually. Look at cmd_descs.yaml if you want to update commands.
//

#include <rz_cmd.h>
#include <rz_core.h>
#include <rz_util.h>

// Command handlers, manually defined somewhere else
// "fridas"
RZ_IPI RzCmdStatus rz_cmd_fridas_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "fridau"
RZ_IPI RzCmdStatus rz_cmd_fridau_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "fridad"
RZ_IPI RzCmdStatus rz_cmd_fridad_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "fridap"
RZ_IPI RzCmdStatus rz_cmd_fridap_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "fridaa"
RZ_IPI RzCmdStatus rz_cmd_fridaa_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "fridao"
RZ_IPI RzCmdStatus rz_cmd_fridao_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "fridar"
RZ_IPI RzCmdStatus rz_cmd_fridar_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "fridac"
RZ_IPI RzCmdStatus rz_cmd_fridac_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "fridae"
RZ_IPI RzCmdStatus rz_cmd_fridae_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "fridal"
RZ_IPI RzCmdStatus rz_cmd_fridal_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "fridai"
RZ_IPI RzCmdStatus rz_cmd_fridai_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "fridam"
RZ_IPI RzCmdStatus rz_cmd_fridam_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "fridax"
RZ_IPI RzCmdStatus rz_cmd_fridax_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "fridaw"
RZ_IPI RzCmdStatus rz_cmd_fridaw_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "fridaR"
RZ_IPI RzCmdStatus rz_cmd_fridaR_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "fridat"
RZ_IPI RzCmdStatus rz_cmd_fridat_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "fridaM"
RZ_IPI RzCmdStatus rz_cmd_fridaM_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "fridaE"
RZ_IPI RzCmdStatus rz_cmd_fridaE_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "fridaI"
RZ_IPI RzCmdStatus rz_cmd_fridaI_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "fridaS"
RZ_IPI RzCmdStatus rz_cmd_fridaS_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "fridab"
RZ_IPI RzCmdStatus rz_cmd_fridab_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "fridab-"
RZ_IPI RzCmdStatus rz_cmd_fridab_minus_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "fridag"
RZ_IPI RzCmdStatus rz_cmd_fridag_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "fridaB"
RZ_IPI RzCmdStatus rz_cmd_fridaB_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "fridaW"
RZ_IPI RzCmdStatus rz_cmd_fridaW_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "fridaW-"
RZ_IPI RzCmdStatus rz_cmd_fridaW_minus_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "fridaJ"
RZ_IPI RzCmdStatus rz_cmd_fridaJ_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "fridaL"
RZ_IPI RzCmdStatus rz_cmd_fridaL_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "fridaC"
RZ_IPI RzCmdStatus rz_cmd_fridaC_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "fridaN"
RZ_IPI RzCmdStatus rz_cmd_fridaN_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "fridaD"
RZ_IPI RzCmdStatus rz_cmd_fridaD_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
RZ_IPI char **rz_frida_autocomplete_class(RzCore *core);
// "fridaIm"
RZ_IPI RzCmdStatus rz_cmd_fridaIm_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);

// Main function that initialize the entire commands tree
RZ_IPI void rzshell_cmddescs_init(RzCore *core);
