// SPDX-FileCopyrightText: 2021-2026 RizinOrg <info@rizin.re>
// SPDX-License-Identifier: LGPL-3.0-only
//
// WARNING: This file was auto-generated by cmd_descs_generate.py script. Do not
// modify it manually. Look at cmd_descs.yaml if you want to update commands.
//

#include <cmd_descs.h>

static const RzCmdDescDetail cmd_fridau_details[3];
static const RzCmdDescDetail cmd_fridap_details[2];
static const RzCmdDescDetail cmd_fridaa_details[2];
static const RzCmdDescDetail cmd_fridao_details[2];
static const RzCmdDescDetail cmd_fridae_details[2];
static const RzCmdDescDetail cmd_fridal_details[2];
static const RzCmdDescDetail cmd_fridax_details[2];
static const RzCmdDescDetail cmd_fridaw_details[2];
static const RzCmdDescDetail cmd_fridaR_details[2];
static const RzCmdDescDetail cmd_fridaM_details[2];
static const RzCmdDescDetail cmd_fridaE_details[2];
static const RzCmdDescDetail cmd_fridaI_details[2];
static const RzCmdDescDetail cmd_fridaS_details[2];
static const RzCmdDescDetail cmd_fridab_details[2];
static const RzCmdDescDetail cmd_fridab_minus_details[2];
static const RzCmdDescDetail cmd_fridag_details[2];
static const RzCmdDescDetail cmd_fridaB_details[2];
static const RzCmdDescDetail cmd_fridaW_details[2];
static const RzCmdDescDetail cmd_fridaW_minus_details[2];
static const RzCmdDescDetail cmd_fridaD_details[2];
static const RzCmdDescDetail cmd_fridaIm_details[2];
static const RzCmdDescDetail cmd_frida_details[11];
static const RzCmdDescArg cmd_fridau_args[2];
static const RzCmdDescArg cmd_fridap_args[2];
static const RzCmdDescArg cmd_fridaa_args[2];
static const RzCmdDescArg cmd_fridao_args[2];
static const RzCmdDescArg cmd_fridae_args[2];
static const RzCmdDescArg cmd_fridal_args[2];
static const RzCmdDescArg cmd_fridax_args[3];
static const RzCmdDescArg cmd_fridaw_args[3];
static const RzCmdDescArg cmd_fridaR_args[2];
static const RzCmdDescArg cmd_fridaM_args[2];
static const RzCmdDescArg cmd_fridaE_args[2];
static const RzCmdDescArg cmd_fridaI_args[2];
static const RzCmdDescArg cmd_fridaS_args[2];
static const RzCmdDescArg cmd_fridab_args[2];
static const RzCmdDescArg cmd_fridab_minus_args[2];
static const RzCmdDescArg cmd_fridag_args[2];
static const RzCmdDescArg cmd_fridaB_args[4];
static const RzCmdDescArg cmd_fridaW_args[4];
static const RzCmdDescArg cmd_fridaW_minus_args[2];
static const RzCmdDescArg cmd_fridaC_args[2];
static const RzCmdDescArg cmd_fridaN_args[2];
static const RzCmdDescArg cmd_fridaRN_args[2];
static const RzCmdDescArg cmd_fridaD_args[3];
static const RzCmdDescArg cmd_fridaIm_args[3];

static const RzCmdDescDetailEntry cmd_frida_Session_space_status_detail_entries[] = {
	{ .text = "fridas", .arg_str = NULL, .comment = "Print plugin/session status in plain text" },
	{ .text = "fridasj", .arg_str = NULL, .comment = "Print plugin/session status as JSON" },
	{ 0 },
};

static const RzCmdDescDetailEntry cmd_frida_URI_space_grammar_detail_entries[] = {
	{ .text = "fridau ", .arg_str = "frida://attach/local//1234", .comment = "Validate URI for attaching to local PID 1234" },
	{ .text = "fridau ", .arg_str = "frida://spawn/usb/device-1/com.example.app", .comment = "Validate URI for spawning an Android package over USB" },
	{ .text = "fridau ", .arg_str = "frida://attach/remote/127.0.0.1:27042/4321", .comment = "Validate URI for attaching to PID 4321 over remote frida-server" },
	{ .text = "fridauj ", .arg_str = "frida://launch/local///bin/ls", .comment = "Validate launch URI for /bin/ls and emit JSON" },
	{ 0 },
};

static const RzCmdDescDetailEntry cmd_frida_Device_space_enumeration_detail_entries[] = {
	{ .text = "fridadj", .arg_str = NULL, .comment = "Enumerate connected Frida devices as JSON" },
	{ 0 },
};

static const RzCmdDescDetailEntry cmd_frida_Process_space_listing_detail_entries[] = {
	{ .text = "fridapj", .arg_str = NULL, .comment = "Enumerate local processes as JSON" },
	{ .text = "fridapj ", .arg_str = "frida://list/usb/device-1/", .comment = "Enumerate processes on a USB device as JSON" },
	{ 0 },
};

static const RzCmdDescDetailEntry cmd_frida_Application_space_listing_detail_entries[] = {
	{ .text = "fridaaj", .arg_str = NULL, .comment = "Enumerate local applications as JSON" },
	{ .text = "fridaaj ", .arg_str = "frida://apps/usb/device-1/", .comment = "Enumerate applications on a USB device as JSON" },
	{ 0 },
};

static const RzCmdDescDetailEntry cmd_frida_Session_space_control_detail_entries[] = {
	{ .text = "fridaoj ", .arg_str = "frida://spawn/local///bin/ls", .comment = "Spawn /bin/ls suspended and open a session" },
	{ .text = "fridarj", .arg_str = NULL, .comment = "Resume the spawned target" },
	{ .text = "fridacj", .arg_str = NULL, .comment = "Close the open session" },
	{ 0 },
};

static const RzCmdDescDetailEntry cmd_frida_Script_space_execution_detail_entries[] = {
	{ .text = "fridaij", .arg_str = NULL, .comment = "Ping the agent and read its version and target info" },
	{ .text = "fridaej ", .arg_str = "Process.arch", .comment = "Evaluate a JavaScript expression in the target process" },
	{ .text = "fridalj ", .arg_str = "hook.js", .comment = "Load and evaluate a JavaScript file in the target process" },
	{ .text = "fridamj", .arg_str = NULL, .comment = "Read buffered agent log, error, and send messages" },
	{ 0 },
};

static const RzCmdDescDetailEntry cmd_frida_Memory_space_access_detail_entries[] = {
	{ .text = "fridaxj ", .arg_str = "0x1000 64", .comment = "Read 64 bytes of the target memory as hex" },
	{ .text = "fridawj ", .arg_str = "0x1000 deadbeef", .comment = "Write four bytes into the target memory" },
	{ 0 },
};

static const RzCmdDescDetailEntry cmd_frida_Runtime_space_info_detail_entries[] = {
	{ .text = "fridaRj", .arg_str = NULL, .comment = "List the target memory ranges" },
	{ .text = "fridatj", .arg_str = NULL, .comment = "List the target threads" },
	{ .text = "fridaMj", .arg_str = NULL, .comment = "List the target modules" },
	{ .text = "fridaEj ", .arg_str = "libc.so", .comment = "List the exports of a module" },
	{ .text = "fridaIj ", .arg_str = "libc.so", .comment = "List the imports of a module" },
	{ .text = "fridaSj ", .arg_str = "libc.so", .comment = "List the symbols of a module" },
	{ 0 },
};

static const RzCmdDescDetailEntry cmd_frida_Debugging_detail_entries[] = {
	{ .text = "fridabj ", .arg_str = "0x1000", .comment = "Set a breakpoint at an address" },
	{ .text = "fridabj", .arg_str = NULL, .comment = "List the breakpoints that are set" },
	{ .text = "fridab-j ", .arg_str = "0x1000", .comment = "Remove a breakpoint, or use * for all" },
	{ .text = "fridagj", .arg_str = NULL, .comment = "Continue a thread parked at a breakpoint" },
	{ .text = "fridaBj ", .arg_str = "4242", .comment = "Read the registers of the thread stopped at a breakpoint" },
	{ .text = "fridaBj ", .arg_str = "4242 pc 0x401000", .comment = "Set a register on the stopped thread before continuing" },
	{ .text = "fridaWj ", .arg_str = "0x1000 8 w", .comment = "Watch 8 bytes for writes with a hardware watchpoint" },
	{ .text = "fridaWj", .arg_str = NULL, .comment = "List the hardware watchpoints that are set" },
	{ .text = "fridaW-j ", .arg_str = "0x1000", .comment = "Remove a watchpoint, or use * for all" },
	{ 0 },
};
static const RzCmdDescDetail cmd_frida_details[] = {
	{ .name = "Session status", .entries = cmd_frida_Session_space_status_detail_entries },
	{ .name = "URI grammar", .entries = cmd_frida_URI_space_grammar_detail_entries },
	{ .name = "Device enumeration", .entries = cmd_frida_Device_space_enumeration_detail_entries },
	{ .name = "Process listing", .entries = cmd_frida_Process_space_listing_detail_entries },
	{ .name = "Application listing", .entries = cmd_frida_Application_space_listing_detail_entries },
	{ .name = "Session control", .entries = cmd_frida_Session_space_control_detail_entries },
	{ .name = "Script execution", .entries = cmd_frida_Script_space_execution_detail_entries },
	{ .name = "Memory access", .entries = cmd_frida_Memory_space_access_detail_entries },
	{ .name = "Runtime info", .entries = cmd_frida_Runtime_space_info_detail_entries },
	{ .name = "Debugging", .entries = cmd_frida_Debugging_detail_entries },
	{ 0 },
};
static const RzCmdDescHelp cmd_frida_help = {
	.summary = "Interact with Frida targets",
	.description = "Commands for the rz-frida integration covering plugin and session status, frida:// URI validation, device, process, and application enumeration, and session lifecycle across local, USB, and remote targets.",
	.details = cmd_frida_details,
};
static const RzCmdDescArg cmd_fridas_args[] = {
	{ 0 },
};
static const RzCmdDescHelp cmd_fridas_help = {
	.summary = "Print Frida session status",
	.description = "Reports whether a session is active and prints the current session state (new, resolved, connecting, attached, detaching, closed, or error).",
	.args = cmd_fridas_args,
};

static const RzCmdDescDetailEntry cmd_fridau_URI_space_grammar_detail_entries[] = {
	{ .text = "frida://", .arg_str = "<action>/<transport>/<device>/<target>", .comment = "Full grammar for the frida:// URI" },
	{ .text = "action   ", .arg_str = "= list | apps | attach | spawn | launch", .comment = "Operation requested for the session" },
	{ .text = "transport", .arg_str = "= local | usb | remote", .comment = "Transport used to reach the Frida target" },
	{ .text = "device   ", .arg_str = "= empty | device-id | host:port", .comment = "Empty for local, id for USB, host:port for remote" },
	{ .text = "target   ", .arg_str = "= pid | process-name | package-name | executable-path", .comment = "Target selector required by attach/spawn/launch" },
	{ 0 },
};

static const RzCmdDescDetailEntry cmd_fridau_Examples_detail_entries[] = {
	{ .text = "fridau ", .arg_str = "frida://attach/local//1234", .comment = "Attach to local PID 1234" },
	{ .text = "fridau ", .arg_str = "frida://spawn/usb/device-1/com.example.app", .comment = "Spawn an Android package on a USB device" },
	{ .text = "fridau ", .arg_str = "frida://launch/local///bin/ls", .comment = "Launch /bin/ls locally (note the leading slash in the path)" },
	{ .text = "fridauj ", .arg_str = "frida://attach/remote/127.0.0.1:27042/4321", .comment = "Validate remote-attach URI and emit JSON" },
	{ 0 },
};
static const RzCmdDescDetail cmd_fridau_details[] = {
	{ .name = "URI grammar", .entries = cmd_fridau_URI_space_grammar_detail_entries },
	{ .name = "Examples", .entries = cmd_fridau_Examples_detail_entries },
	{ 0 },
};
static const RzCmdDescArg cmd_fridau_args[] = {
	{
		.name = "uri",
		.type = RZ_CMD_ARG_TYPE_STRING,
		.flags = RZ_CMD_ARG_FLAG_LAST,

	},
	{ 0 },
};
static const RzCmdDescHelp cmd_fridau_help = {
	.summary = "Validate a frida:// URI",
	.description = "Parses and validates a frida:// URI without contacting any Frida device. Useful for verifying URI syntax in scripts or CI before attempting to attach.",
	.details = cmd_fridau_details,
	.args = cmd_fridau_args,
};

static const RzCmdDescArg cmd_fridad_args[] = {
	{ 0 },
};
static const RzCmdDescHelp cmd_fridad_help = {
	.summary = "List Frida devices",
	.description = "Enumerates devices known to the Frida device manager (local, USB, and remote) and emits a structured JSON reply.",
	.args = cmd_fridad_args,
};

static const RzCmdDescDetailEntry cmd_fridap_Examples_detail_entries[] = {
	{ .text = "fridapj", .arg_str = NULL, .comment = "List local processes as JSON, returns a frida_unavailable error if built without frida-core" },
	{ .text = "fridapj ", .arg_str = "frida://list/usb/device-1/", .comment = "List processes on a USB device by id" },
	{ .text = "fridapj ", .arg_str = "frida://list/remote/127.0.0.1:27042/", .comment = "List processes on a remote frida-server" },
	{ 0 },
};
static const RzCmdDescDetail cmd_fridap_details[] = {
	{ .name = "Examples", .entries = cmd_fridap_Examples_detail_entries },
	{ 0 },
};
static const RzCmdDescArg cmd_fridap_args[] = {
	{
		.name = "uri",
		.type = RZ_CMD_ARG_TYPE_STRING,
		.flags = RZ_CMD_ARG_FLAG_LAST,
		.optional = true,

	},
	{ 0 },
};
static const RzCmdDescHelp cmd_fridap_help = {
	.summary = "List processes on a device",
	.description = "Enumerates the processes visible to a Frida device and emits a structured JSON reply. With no argument it lists the local device, or pass a frida:// URI to select a USB or remote device.",
	.details = cmd_fridap_details,
	.args = cmd_fridap_args,
};

static const RzCmdDescDetailEntry cmd_fridaa_Examples_detail_entries[] = {
	{ .text = "fridaaj", .arg_str = NULL, .comment = "List local applications as JSON, returns a frida_unavailable error if built without frida-core" },
	{ .text = "fridaaj ", .arg_str = "frida://apps/usb/device-1/", .comment = "List applications on a USB device by id" },
	{ 0 },
};
static const RzCmdDescDetail cmd_fridaa_details[] = {
	{ .name = "Examples", .entries = cmd_fridaa_Examples_detail_entries },
	{ 0 },
};
static const RzCmdDescArg cmd_fridaa_args[] = {
	{
		.name = "uri",
		.type = RZ_CMD_ARG_TYPE_STRING,
		.flags = RZ_CMD_ARG_FLAG_LAST,
		.optional = true,

	},
	{ 0 },
};
static const RzCmdDescHelp cmd_fridaa_help = {
	.summary = "List applications on a device",
	.description = "Enumerates the applications known to a Frida device and emits a structured JSON reply. With no argument it lists the local device, or pass a frida:// URI to select a USB or remote device. Application listing is most useful for Android and iOS targets reached over USB.",
	.details = cmd_fridaa_details,
	.args = cmd_fridaa_args,
};

static const RzCmdDescDetailEntry cmd_fridao_Examples_detail_entries[] = {
	{ .text = "fridaoj ", .arg_str = "frida://attach/local//1234", .comment = "Attach to local PID 1234" },
	{ .text = "fridaoj ", .arg_str = "frida://attach/usb//com.example.app", .comment = "Attach by process name on the single USB device" },
	{ .text = "fridaoj ", .arg_str = "frida://spawn/usb//com.example.app", .comment = "Spawn an Android package suspended over USB, resume with fridarj" },
	{ .text = "fridaoj ", .arg_str = "frida://launch/local///bin/ls", .comment = "Launch /bin/ls and resume it immediately" },
	{ .text = "fridaoj ", .arg_str = "frida://attach/remote/127.0.0.1:27042/1234", .comment = "Attach to PID 1234 over a remote frida-server" },
	{ 0 },
};
static const RzCmdDescDetail cmd_fridao_details[] = {
	{ .name = "Examples", .entries = cmd_fridao_Examples_detail_entries },
	{ 0 },
};
static const RzCmdDescArg cmd_fridao_args[] = {
	{
		.name = "uri",
		.type = RZ_CMD_ARG_TYPE_STRING,
		.flags = RZ_CMD_ARG_FLAG_LAST,

	},
	{ 0 },
};
static const RzCmdDescHelp cmd_fridao_help = {
	.summary = "Open a Frida session",
	.description = "Opens a session for a frida:// URI on a local, USB, or remote device: attach to a pid or process name, spawn a target suspended, or launch and resume it. Stores the live session and emits a structured JSON reply.",
	.details = cmd_fridao_details,
	.args = cmd_fridao_args,
};

static const RzCmdDescArg cmd_fridar_args[] = {
	{ 0 },
};
static const RzCmdDescHelp cmd_fridar_help = {
	.summary = "Resume the open Frida session",
	.description = "Resumes a target that was spawned suspended by the open command. Emits a structured JSON reply.",
	.args = cmd_fridar_args,
};

static const RzCmdDescArg cmd_fridac_args[] = {
	{ 0 },
};
static const RzCmdDescHelp cmd_fridac_help = {
	.summary = "Close the open Frida session",
	.description = "Detaches the open session and forgets it. A target that was spawned but never resumed is killed. An attached or launched target keeps running. Emits a structured JSON reply.",
	.args = cmd_fridac_args,
};

static const RzCmdDescDetailEntry cmd_fridae_Examples_detail_entries[] = {
	{ .text = "fridaej ", .arg_str = "Process.arch", .comment = "Read the target architecture from the agent" },
	{ .text = "fridaej ", .arg_str = "\"1 + 1\"", .comment = "Evaluate an expression, quote it when it has spaces" },
	{ 0 },
};
static const RzCmdDescDetail cmd_fridae_details[] = {
	{ .name = "Examples", .entries = cmd_fridae_Examples_detail_entries },
	{ 0 },
};
static const RzCmdDescArg cmd_fridae_args[] = {
	{
		.name = "source",
		.type = RZ_CMD_ARG_TYPE_STRING,
		.flags = RZ_CMD_ARG_FLAG_LAST,

	},
	{ 0 },
};
static const RzCmdDescHelp cmd_fridae_help = {
	.summary = "Evaluate JavaScript in the target process",
	.description = "Loads the rz-frida agent into the open session on first use, then evaluates a JavaScript expression inside the target process and returns its value and type. Quote the expression when it contains spaces, or use fridal for a script that lives in a file.",
	.details = cmd_fridae_details,
	.args = cmd_fridae_args,
};

static const RzCmdDescDetailEntry cmd_fridal_Examples_detail_entries[] = {
	{ .text = "fridalj ", .arg_str = "hook.js", .comment = "Evaluate hook.js inside the target process" },
	{ 0 },
};
static const RzCmdDescDetail cmd_fridal_details[] = {
	{ .name = "Examples", .entries = cmd_fridal_Examples_detail_entries },
	{ 0 },
};
static const RzCmdDescArg cmd_fridal_args[] = {
	{
		.name = "file",
		.type = RZ_CMD_ARG_TYPE_FILE,

	},
	{ 0 },
};
static const RzCmdDescHelp cmd_fridal_help = {
	.summary = "Load and evaluate a JavaScript file in the target process",
	.description = "Reads a JavaScript file from disk and evaluates it inside the target process through the rz-frida agent. Useful for instrumentation scripts that are too large to pass on the command line.",
	.details = cmd_fridal_details,
	.args = cmd_fridal_args,
};

static const RzCmdDescArg cmd_fridai_args[] = {
	{ 0 },
};
static const RzCmdDescHelp cmd_fridai_help = {
	.summary = "Ping the agent in the target process",
	.description = "Loads the rz-frida agent into the open session on first use and pings it, returning the agent version and the target platform, architecture, and pointer size. A quick way to check the host-agent message channel is alive.",
	.args = cmd_fridai_args,
};

static const RzCmdDescArg cmd_fridam_args[] = {
	{ 0 },
};
static const RzCmdDescHelp cmd_fridam_help = {
	.summary = "Read buffered agent messages",
	.description = "Drains the asynchronous output captured from the injected agent: console logs, uncaught script errors, and unsolicited send() notifications with any binary data. Returns them as a JSON array and clears the buffer.",
	.args = cmd_fridam_args,
};

static const RzCmdDescDetailEntry cmd_fridax_Examples_detail_entries[] = {
	{ .text = "fridaxj ", .arg_str = "0x1000 64", .comment = "Read 64 bytes at 0x1000 from the target process" },
	{ 0 },
};
static const RzCmdDescDetail cmd_fridax_details[] = {
	{ .name = "Examples", .entries = cmd_fridax_Examples_detail_entries },
	{ 0 },
};
static const RzCmdDescArg cmd_fridax_args[] = {
	{
		.name = "address",
		.type = RZ_CMD_ARG_TYPE_NUM,

	},
	{
		.name = "size",
		.type = RZ_CMD_ARG_TYPE_NUM,

	},
	{ 0 },
};
static const RzCmdDescHelp cmd_fridax_help = {
	.summary = "Read target memory",
	.description = "Reads a block of memory from the target process through the rz-frida agent and returns the bytes as a hex string. Loads the agent into the open session on first use.",
	.details = cmd_fridax_details,
	.args = cmd_fridax_args,
};

static const RzCmdDescDetailEntry cmd_fridaw_Examples_detail_entries[] = {
	{ .text = "fridawj ", .arg_str = "0x1000 deadbeef", .comment = "Write the bytes 'de ad be ef' at 0x1000 in the target" },
	{ 0 },
};
static const RzCmdDescDetail cmd_fridaw_details[] = {
	{ .name = "Examples", .entries = cmd_fridaw_Examples_detail_entries },
	{ 0 },
};
static const RzCmdDescArg cmd_fridaw_args[] = {
	{
		.name = "address",
		.type = RZ_CMD_ARG_TYPE_NUM,

	},
	{
		.name = "bytes",
		.type = RZ_CMD_ARG_TYPE_STRING,
		.flags = RZ_CMD_ARG_FLAG_LAST,

	},
	{ 0 },
};
static const RzCmdDescHelp cmd_fridaw_help = {
	.summary = "Write target memory",
	.description = "Writes a hex byte string into the target process memory through the rz-frida agent and returns the number of bytes written. Loads the agent into the open session on first use.",
	.details = cmd_fridaw_details,
	.args = cmd_fridaw_args,
};

static const RzCmdDescDetailEntry cmd_fridaR_Examples_detail_entries[] = {
	{ .text = "fridaRj", .arg_str = NULL, .comment = "List the cached target memory ranges" },
	{ .text = "fridaRj ", .arg_str = "refresh", .comment = "Re-enumerate the ranges instead of using the cache" },
	{ 0 },
};
static const RzCmdDescDetail cmd_fridaR_details[] = {
	{ .name = "Examples", .entries = cmd_fridaR_Examples_detail_entries },
	{ 0 },
};
static const RzCmdDescArg cmd_fridaR_args[] = {
	{
		.name = "refresh",
		.type = RZ_CMD_ARG_TYPE_STRING,
		.flags = RZ_CMD_ARG_FLAG_LAST,
		.optional = true,

	},
	{ 0 },
};
static const RzCmdDescHelp cmd_fridaR_help = {
	.summary = "List target memory ranges",
	.description = "Lists the memory ranges of the target process through the rz-frida agent, each with its base, size, protection, and backing file when mapped. The agent caches the list and re-enumerates it after code runs in the target, pass any argument to force a fresh enumeration. Loads the agent into the open session on first use.",
	.details = cmd_fridaR_details,
	.args = cmd_fridaR_args,
};

static const RzCmdDescArg cmd_fridat_args[] = {
	{ 0 },
};
static const RzCmdDescHelp cmd_fridat_help = {
	.summary = "List target threads",
	.description = "Lists the threads of the target process through the rz-frida agent, each with its id and state. Loads the agent into the open session on first use.",
	.args = cmd_fridat_args,
};

static const RzCmdDescDetailEntry cmd_fridaM_Examples_detail_entries[] = {
	{ .text = "fridaMj", .arg_str = NULL, .comment = "List the cached target modules" },
	{ .text = "fridaMj ", .arg_str = "refresh", .comment = "Re-enumerate the modules instead of using the cache" },
	{ 0 },
};
static const RzCmdDescDetail cmd_fridaM_details[] = {
	{ .name = "Examples", .entries = cmd_fridaM_Examples_detail_entries },
	{ 0 },
};
static const RzCmdDescArg cmd_fridaM_args[] = {
	{
		.name = "refresh",
		.type = RZ_CMD_ARG_TYPE_STRING,
		.flags = RZ_CMD_ARG_FLAG_LAST,
		.optional = true,

	},
	{ 0 },
};
static const RzCmdDescHelp cmd_fridaM_help = {
	.summary = "List target modules",
	.description = "Lists the modules loaded in the target process through the rz-frida agent, each with its name, base, size, and path. The agent caches the list and re-enumerates it after code runs in the target, pass any argument to force a fresh enumeration. Loads the agent into the open session on first use.",
	.details = cmd_fridaM_details,
	.args = cmd_fridaM_args,
};

static const RzCmdDescDetailEntry cmd_fridaE_Examples_detail_entries[] = {
	{ .text = "fridaEj ", .arg_str = "libc.so", .comment = "List the exports of libc.so in the target" },
	{ 0 },
};
static const RzCmdDescDetail cmd_fridaE_details[] = {
	{ .name = "Examples", .entries = cmd_fridaE_Examples_detail_entries },
	{ 0 },
};
static const RzCmdDescArg cmd_fridaE_args[] = {
	{
		.name = "module",
		.type = RZ_CMD_ARG_TYPE_STRING,
		.flags = RZ_CMD_ARG_FLAG_LAST,

	},
	{ 0 },
};
static const RzCmdDescHelp cmd_fridaE_help = {
	.summary = "List target module exports",
	.description = "Lists the exports of a module loaded in the target process through the rz-frida agent, each with its type, name, and address. Loads the agent into the open session on first use.",
	.details = cmd_fridaE_details,
	.args = cmd_fridaE_args,
};

static const RzCmdDescDetailEntry cmd_fridaI_Examples_detail_entries[] = {
	{ .text = "fridaIj ", .arg_str = "libc.so", .comment = "List the imports of libc.so in the target" },
	{ 0 },
};
static const RzCmdDescDetail cmd_fridaI_details[] = {
	{ .name = "Examples", .entries = cmd_fridaI_Examples_detail_entries },
	{ 0 },
};
static const RzCmdDescArg cmd_fridaI_args[] = {
	{
		.name = "module",
		.type = RZ_CMD_ARG_TYPE_STRING,
		.flags = RZ_CMD_ARG_FLAG_LAST,

	},
	{ 0 },
};
static const RzCmdDescHelp cmd_fridaI_help = {
	.summary = "List target module imports",
	.description = "Lists the imports of a module loaded in the target process through the rz-frida agent, each with its type, name, source module, and address. Loads the agent into the open session on first use.",
	.details = cmd_fridaI_details,
	.args = cmd_fridaI_args,
};

static const RzCmdDescDetailEntry cmd_fridaS_Examples_detail_entries[] = {
	{ .text = "fridaSj ", .arg_str = "libc.so", .comment = "List the symbols of libc.so in the target" },
	{ 0 },
};
static const RzCmdDescDetail cmd_fridaS_details[] = {
	{ .name = "Examples", .entries = cmd_fridaS_Examples_detail_entries },
	{ 0 },
};
static const RzCmdDescArg cmd_fridaS_args[] = {
	{
		.name = "module",
		.type = RZ_CMD_ARG_TYPE_STRING,
		.flags = RZ_CMD_ARG_FLAG_LAST,

	},
	{ 0 },
};
static const RzCmdDescHelp cmd_fridaS_help = {
	.summary = "List target module symbols",
	.description = "Lists the symbols of a module loaded in the target process through the rz-frida agent, each with its name, address, and type. The list is empty for a module that carries no symbol table. Loads the agent into the open session on first use.",
	.details = cmd_fridaS_details,
	.args = cmd_fridaS_args,
};

static const RzCmdDescDetailEntry cmd_fridab_Examples_detail_entries[] = {
	{ .text = "fridabj ", .arg_str = "0x1000", .comment = "Set a breakpoint at 0x1000 in the target" },
	{ .text = "fridabj", .arg_str = NULL, .comment = "List the breakpoints that are set" },
	{ 0 },
};
static const RzCmdDescDetail cmd_fridab_details[] = {
	{ .name = "Examples", .entries = cmd_fridab_Examples_detail_entries },
	{ 0 },
};
static const RzCmdDescArg cmd_fridab_args[] = {
	{
		.name = "address",
		.type = RZ_CMD_ARG_TYPE_NUM,
		.optional = true,

	},
	{ 0 },
};
static const RzCmdDescHelp cmd_fridab_help = {
	.summary = "Set or list native breakpoints",
	.description = "Sets a breakpoint at an address in the target process through the rz-frida agent, or lists the breakpoints that are set when called with no argument. A hit is reported asynchronously through fridam with the thread id and register context, and the thread stays parked until fridag continues it. Loads the agent into the open session on first use.",
	.details = cmd_fridab_details,
	.args = cmd_fridab_args,
};

static const RzCmdDescDetailEntry cmd_fridab_minus_Examples_detail_entries[] = {
	{ .text = "fridab-j ", .arg_str = "0x1000", .comment = "Remove the breakpoint at 0x1000" },
	{ .text = "fridab-j ", .arg_str = "*", .comment = "Remove every breakpoint" },
	{ 0 },
};
static const RzCmdDescDetail cmd_fridab_minus_details[] = {
	{ .name = "Examples", .entries = cmd_fridab_minus_Examples_detail_entries },
	{ 0 },
};
static const RzCmdDescArg cmd_fridab_minus_args[] = {
	{
		.name = "address",
		.type = RZ_CMD_ARG_TYPE_STRING,
		.flags = RZ_CMD_ARG_FLAG_LAST,

	},
	{ 0 },
};
static const RzCmdDescHelp cmd_fridab_minus_help = {
	.summary = "Remove native breakpoints",
	.description = "Removes the breakpoint at an address in the target process through the rz-frida agent, or every breakpoint when the address is *. Loads the agent into the open session on first use.",
	.details = cmd_fridab_minus_details,
	.args = cmd_fridab_minus_args,
};

static const RzCmdDescDetailEntry cmd_fridag_Examples_detail_entries[] = {
	{ .text = "fridagj", .arg_str = NULL, .comment = "Continue the most recently parked thread" },
	{ .text = "fridagj ", .arg_str = "4242", .comment = "Continue the thread with id 4242" },
	{ 0 },
};
static const RzCmdDescDetail cmd_fridag_details[] = {
	{ .name = "Examples", .entries = cmd_fridag_Examples_detail_entries },
	{ 0 },
};
static const RzCmdDescArg cmd_fridag_args[] = {
	{
		.name = "thread",
		.type = RZ_CMD_ARG_TYPE_NUM,
		.optional = true,

	},
	{ 0 },
};
static const RzCmdDescHelp cmd_fridag_help = {
	.summary = "Continue a thread parked at a breakpoint",
	.description = "Continues a thread parked at a breakpoint in the target process through the rz-frida agent. With a thread id it continues that exact thread, with no argument it continues the most recently parked thread, and reports whether a thread was released. Loads the agent into the open session on first use.",
	.details = cmd_fridag_details,
	.args = cmd_fridag_args,
};

static const RzCmdDescDetailEntry cmd_fridaB_Examples_detail_entries[] = {
	{ .text = "fridaBj ", .arg_str = "4242", .comment = "Read the registers of the thread with id 4242" },
	{ .text = "fridaBj ", .arg_str = "4242 pc 0x401000", .comment = "Set pc on thread 4242 before continuing it with fridagj" },
	{ 0 },
};
static const RzCmdDescDetail cmd_fridaB_details[] = {
	{ .name = "Examples", .entries = cmd_fridaB_Examples_detail_entries },
	{ 0 },
};
static const RzCmdDescArg cmd_fridaB_args[] = {
	{
		.name = "thread",
		.type = RZ_CMD_ARG_TYPE_NUM,

	},
	{
		.name = "register",
		.type = RZ_CMD_ARG_TYPE_STRING,
		.optional = true,

	},
	{
		.name = "value",
		.type = RZ_CMD_ARG_TYPE_NUM,
		.optional = true,

	},
	{ 0 },
};
static const RzCmdDescHelp cmd_fridaB_help = {
	.summary = "Read or write registers at a breakpoint stop",
	.description = "Reads the saved register context of a thread parked at a breakpoint in the target process through the rz-frida agent, or sets one register when a register name and value follow the thread id. A write lands on the saved context and takes effect when the thread is continued with fridag. Loads the agent into the open session on first use.",
	.details = cmd_fridaB_details,
	.args = cmd_fridaB_args,
};

static const RzCmdDescDetailEntry cmd_fridaW_Examples_detail_entries[] = {
	{ .text = "fridaWj ", .arg_str = "0x1000", .comment = "Watch the pointer-sized word at 0x1000 for reads and writes" },
	{ .text = "fridaWj ", .arg_str = "0x1000 8 w", .comment = "Watch 8 bytes at 0x1000 for writes only" },
	{ .text = "fridaWj", .arg_str = NULL, .comment = "List the watchpoints that are set" },
	{ 0 },
};
static const RzCmdDescDetail cmd_fridaW_details[] = {
	{ .name = "Examples", .entries = cmd_fridaW_Examples_detail_entries },
	{ 0 },
};
static const RzCmdDescArg cmd_fridaW_args[] = {
	{
		.name = "address",
		.type = RZ_CMD_ARG_TYPE_NUM,
		.optional = true,

	},
	{
		.name = "size",
		.type = RZ_CMD_ARG_TYPE_NUM,
		.optional = true,

	},
	{
		.name = "conditions",
		.type = RZ_CMD_ARG_TYPE_STRING,
		.flags = RZ_CMD_ARG_FLAG_LAST,
		.optional = true,

	},
	{ 0 },
};
static const RzCmdDescHelp cmd_fridaW_help = {
	.summary = "Set or list hardware watchpoints",
	.description = "Sets a hardware watchpoint on an address in the target process through the rz-frida agent, or lists the watchpoints that are set when called with no argument. The optional size defaults to the pointer size and the optional conditions are r, w, or rw (default rw). The watchpoint is armed on every target thread, an access is reported asynchronously through fridam as a frida.wp event with the faulting thread, program counter, and register context, and the watchpoint disarms itself on that hit. The CPU has a small fixed number of watchpoint slots. Loads the agent into the open session on first use.",
	.details = cmd_fridaW_details,
	.args = cmd_fridaW_args,
};

static const RzCmdDescDetailEntry cmd_fridaW_minus_Examples_detail_entries[] = {
	{ .text = "fridaW-j ", .arg_str = "0x1000", .comment = "Remove the watchpoint at 0x1000" },
	{ .text = "fridaW-j ", .arg_str = "*", .comment = "Remove every watchpoint" },
	{ 0 },
};
static const RzCmdDescDetail cmd_fridaW_minus_details[] = {
	{ .name = "Examples", .entries = cmd_fridaW_minus_Examples_detail_entries },
	{ 0 },
};
static const RzCmdDescArg cmd_fridaW_minus_args[] = {
	{
		.name = "address",
		.type = RZ_CMD_ARG_TYPE_STRING,
		.flags = RZ_CMD_ARG_FLAG_LAST,

	},
	{ 0 },
};
static const RzCmdDescHelp cmd_fridaW_minus_help = {
	.summary = "Remove hardware watchpoints",
	.description = "Removes the hardware watchpoint at an address in the target process through the rz-frida agent, or every watchpoint when the address is *. Loads the agent into the open session on first use.",
	.details = cmd_fridaW_minus_details,
	.args = cmd_fridaW_minus_args,
};

static const RzCmdDescArg cmd_fridaJ_args[] = {
	{ 0 },
};
static const RzCmdDescHelp cmd_fridaJ_help = {
	.summary = "Check whether the Android Java VM is reachable",
	.description = "Checks whether the Java VM (ART) is available in the target process and reports whether Java instrumentation is possible. Requires an Android target with the frida-java-bridge bundled into the agent.",
	.args = cmd_fridaJ_args,
};

static const RzCmdDescArg cmd_fridaL_args[] = {
	{ 0 },
};
static const RzCmdDescHelp cmd_fridaL_help = {
	.summary = "Enumerate Java classloaders in the target",
	.description = "Enumerates the classloaders in the target process through the rz-frida agent and assigns each one a stable integer id for the current session. Requires an Android target with the Java VM available.",
	.args = cmd_fridaL_args,
};

static const RzCmdDescArg cmd_fridaC_args[] = {
	{
		.name = "prefix",
		.type = RZ_CMD_ARG_TYPE_STRING,
		.flags = RZ_CMD_ARG_FLAG_LAST,
		.optional = true,

	},
	{ 0 },
};
static const RzCmdDescHelp cmd_fridaC_help = {
	.summary = "Enumerate loaded Java classes in the target",
	.description = "Enumerates the loaded Java classes in the target process through the rz-frida agent. An optional prefix narrows the list to classes whose canonical name starts with that string. The frida.java.max config (default 512) caps the batch; zero means unlimited.",
	.args = cmd_fridaC_args,
};

static const RzCmdDescArg cmd_fridaN_args[] = {
	{
		.name = "mode",
		.type = RZ_CMD_ARG_TYPE_STRING,
		.flags = RZ_CMD_ARG_FLAG_LAST,
		.optional = true,

	},
	{ 0 },
};
static const RzCmdDescHelp cmd_fridaN_help = {
	.summary = "Monitor newly loaded Java classes in the target",
	.description = "When called without arguments, lists classes loaded since the monitor was last started. Call 'fridaNj start' to enable classload hooks on all active classloaders and intercept new classloader creation. Call 'fridaNj stop' to detach the hooks and clear the tracking buffer. Requires an Android target with the Java VM available.",
	.args = cmd_fridaN_args,
};

static const RzCmdDescArg cmd_fridaRN_args[] = {
	{
		.name = "mode",
		.type = RZ_CMD_ARG_TYPE_STRING,
		.flags = RZ_CMD_ARG_FLAG_LAST,
		.optional = true,

	},
	{ 0 },
};
static const RzCmdDescHelp cmd_fridaRN_help = {
	.summary = "Hook RegisterNatives to map native methods to addresses",
	.description = "When called without arguments, lists captured JNI RegisterNatives invocations with className, method names, signatures and native function addresses. Call 'fridaRNj on' to arm the low-level JNI hook on the ART runtime (JNI function table offset 215). 'fridaRNj off' disarms and clears the buffer. 'fridaRNj import' imports the captured native method addresses into the rizin analysis class database. Requires an Android target with the Java VM available.",
	.args = cmd_fridaRN_args,
};

static const RzCmdDescArg cmd_fridaf_args[] = {
	{ 0 },
};
static const RzCmdDescHelp cmd_fridaf_help = {
	.summary = "Import runtime modules as rizin flags",
	.description = "Enumerates the target process modules via the rz-frida agent and imports their base addresses into the frida.libs flag space as rizin flags. Returns the count of modules imported.",
	.args = cmd_fridaf_args,
};

static const RzCmdDescDetailEntry cmd_fridaD_Examples_detail_entries[] = {
	{ .text = "fridaDj ", .arg_str = "java.lang.String", .comment = "Describe String using the default system loader, Tab to autocomplete class names" },
	{ .text = "fridaDj ", .arg_str = "com.example.Foo 3", .comment = "Describe Foo loaded by classloader id 3" },
	{ 0 },
};
static const RzCmdDescDetail cmd_fridaD_details[] = {
	{ .name = "Examples", .entries = cmd_fridaD_Examples_detail_entries },
	{ 0 },
};
static const RzCmdDescArg cmd_fridaD_args[] = {
	{
		.name = "class",
		.type = RZ_CMD_ARG_TYPE_CHOICES,
		.choices.choices_cb = rz_frida_autocomplete_class,

	},
	{
		.name = "loader",
		.type = RZ_CMD_ARG_TYPE_NUM,
		.optional = true,

	},
	{ 0 },
};
static const RzCmdDescHelp cmd_fridaD_help = {
	.summary = "Describe a Java class in the target",
	.description = "Describes a Java class in the target process through the rz-frida agent. Takes a fully qualified class name and an optional classloader id from a prior loader listing, extracts the superclass, interfaces, declared fields, declared methods, constructors, modifier flags, and Kotlin metadata when the class was compiled with the Kotlin compiler, and returns everything in a structured JSON envelope.",
	.details = cmd_fridaD_details,
	.args = cmd_fridaD_args,
};

static const RzCmdDescDetailEntry cmd_fridaIm_Examples_detail_entries[] = {
	{ .text = "fridaImj ", .arg_str = "java.lang.String", .comment = "Import String using the default system loader, Tab to autocomplete class names" },
	{ .text = "fridaImj ", .arg_str = "com.example.Foo 3", .comment = "Import Foo loaded by classloader id 3" },
	{ 0 },
};
static const RzCmdDescDetail cmd_fridaIm_details[] = {
	{ .name = "Examples", .entries = cmd_fridaIm_Examples_detail_entries },
	{ 0 },
};
static const RzCmdDescArg cmd_fridaIm_args[] = {
	{
		.name = "class",
		.type = RZ_CMD_ARG_TYPE_CHOICES,
		.choices.choices_cb = rz_frida_autocomplete_class,

	},
	{
		.name = "loader",
		.type = RZ_CMD_ARG_TYPE_NUM,
		.optional = true,

	},
	{ 0 },
};
static const RzCmdDescHelp cmd_fridaIm_help = {
	.summary = "Import a Java class description into rizin analysis",
	.description = "Describes a Java class in the target through the rz-frida agent and imports its name, superclass, methods, and constructors into the rizin analysis class database. After import the class is visible with ac and acl. Takes a fully qualified class name and an optional classloader id.",
	.details = cmd_fridaIm_details,
	.args = cmd_fridaIm_args,
};

RZ_IPI void rzshell_cmddescs_init(RzCore *core) {
	RzCmdDesc *root_cd = rz_cmd_get_root(core->rcmd);
	rz_cmd_batch_start(core->rcmd);

	RzCmdDesc *cmd_frida_cd = rz_cmd_desc_group_new(core->rcmd, root_cd, "frida", NULL, NULL, &cmd_frida_help);
	rz_warn_if_fail(cmd_frida_cd);
	RzCmdDesc *cmd_fridas_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridas", RZ_OUTPUT_MODE_STANDARD | RZ_OUTPUT_MODE_JSON, rz_cmd_fridas_handler, &cmd_fridas_help);
	rz_warn_if_fail(cmd_fridas_cd);

	RzCmdDesc *cmd_fridau_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridau", RZ_OUTPUT_MODE_STANDARD | RZ_OUTPUT_MODE_JSON, rz_cmd_fridau_handler, &cmd_fridau_help);
	rz_warn_if_fail(cmd_fridau_cd);

	RzCmdDesc *cmd_fridad_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridad", RZ_OUTPUT_MODE_JSON, rz_cmd_fridad_handler, &cmd_fridad_help);
	rz_warn_if_fail(cmd_fridad_cd);

	RzCmdDesc *cmd_fridap_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridap", RZ_OUTPUT_MODE_JSON, rz_cmd_fridap_handler, &cmd_fridap_help);
	rz_warn_if_fail(cmd_fridap_cd);

	RzCmdDesc *cmd_fridaa_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridaa", RZ_OUTPUT_MODE_JSON, rz_cmd_fridaa_handler, &cmd_fridaa_help);
	rz_warn_if_fail(cmd_fridaa_cd);

	RzCmdDesc *cmd_fridao_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridao", RZ_OUTPUT_MODE_JSON, rz_cmd_fridao_handler, &cmd_fridao_help);
	rz_warn_if_fail(cmd_fridao_cd);

	RzCmdDesc *cmd_fridar_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridar", RZ_OUTPUT_MODE_JSON, rz_cmd_fridar_handler, &cmd_fridar_help);
	rz_warn_if_fail(cmd_fridar_cd);

	RzCmdDesc *cmd_fridac_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridac", RZ_OUTPUT_MODE_JSON, rz_cmd_fridac_handler, &cmd_fridac_help);
	rz_warn_if_fail(cmd_fridac_cd);

	RzCmdDesc *cmd_fridae_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridae", RZ_OUTPUT_MODE_JSON, rz_cmd_fridae_handler, &cmd_fridae_help);
	rz_warn_if_fail(cmd_fridae_cd);

	RzCmdDesc *cmd_fridal_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridal", RZ_OUTPUT_MODE_JSON, rz_cmd_fridal_handler, &cmd_fridal_help);
	rz_warn_if_fail(cmd_fridal_cd);

	RzCmdDesc *cmd_fridai_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridai", RZ_OUTPUT_MODE_JSON, rz_cmd_fridai_handler, &cmd_fridai_help);
	rz_warn_if_fail(cmd_fridai_cd);

	RzCmdDesc *cmd_fridam_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridam", RZ_OUTPUT_MODE_JSON, rz_cmd_fridam_handler, &cmd_fridam_help);
	rz_warn_if_fail(cmd_fridam_cd);

	RzCmdDesc *cmd_fridax_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridax", RZ_OUTPUT_MODE_JSON, rz_cmd_fridax_handler, &cmd_fridax_help);
	rz_warn_if_fail(cmd_fridax_cd);

	RzCmdDesc *cmd_fridaw_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridaw", RZ_OUTPUT_MODE_JSON, rz_cmd_fridaw_handler, &cmd_fridaw_help);
	rz_warn_if_fail(cmd_fridaw_cd);

	RzCmdDesc *cmd_fridaR_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridaR", RZ_OUTPUT_MODE_JSON, rz_cmd_fridaR_handler, &cmd_fridaR_help);
	rz_warn_if_fail(cmd_fridaR_cd);

	RzCmdDesc *cmd_fridat_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridat", RZ_OUTPUT_MODE_JSON, rz_cmd_fridat_handler, &cmd_fridat_help);
	rz_warn_if_fail(cmd_fridat_cd);

	RzCmdDesc *cmd_fridaM_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridaM", RZ_OUTPUT_MODE_JSON, rz_cmd_fridaM_handler, &cmd_fridaM_help);
	rz_warn_if_fail(cmd_fridaM_cd);

	RzCmdDesc *cmd_fridaE_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridaE", RZ_OUTPUT_MODE_JSON, rz_cmd_fridaE_handler, &cmd_fridaE_help);
	rz_warn_if_fail(cmd_fridaE_cd);

	RzCmdDesc *cmd_fridaI_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridaI", RZ_OUTPUT_MODE_JSON, rz_cmd_fridaI_handler, &cmd_fridaI_help);
	rz_warn_if_fail(cmd_fridaI_cd);

	RzCmdDesc *cmd_fridaS_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridaS", RZ_OUTPUT_MODE_JSON, rz_cmd_fridaS_handler, &cmd_fridaS_help);
	rz_warn_if_fail(cmd_fridaS_cd);

	RzCmdDesc *cmd_fridab_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridab", RZ_OUTPUT_MODE_JSON, rz_cmd_fridab_handler, &cmd_fridab_help);
	rz_warn_if_fail(cmd_fridab_cd);

	RzCmdDesc *cmd_fridab_minus_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridab-", RZ_OUTPUT_MODE_JSON, rz_cmd_fridab_minus_handler, &cmd_fridab_minus_help);
	rz_warn_if_fail(cmd_fridab_minus_cd);

	RzCmdDesc *cmd_fridag_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridag", RZ_OUTPUT_MODE_JSON, rz_cmd_fridag_handler, &cmd_fridag_help);
	rz_warn_if_fail(cmd_fridag_cd);

	RzCmdDesc *cmd_fridaB_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridaB", RZ_OUTPUT_MODE_JSON, rz_cmd_fridaB_handler, &cmd_fridaB_help);
	rz_warn_if_fail(cmd_fridaB_cd);

	RzCmdDesc *cmd_fridaW_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridaW", RZ_OUTPUT_MODE_JSON, rz_cmd_fridaW_handler, &cmd_fridaW_help);
	rz_warn_if_fail(cmd_fridaW_cd);

	RzCmdDesc *cmd_fridaW_minus_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridaW-", RZ_OUTPUT_MODE_JSON, rz_cmd_fridaW_minus_handler, &cmd_fridaW_minus_help);
	rz_warn_if_fail(cmd_fridaW_minus_cd);

	RzCmdDesc *cmd_fridaJ_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridaJ", RZ_OUTPUT_MODE_JSON, rz_cmd_fridaJ_handler, &cmd_fridaJ_help);
	rz_warn_if_fail(cmd_fridaJ_cd);

	RzCmdDesc *cmd_fridaL_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridaL", RZ_OUTPUT_MODE_JSON, rz_cmd_fridaL_handler, &cmd_fridaL_help);
	rz_warn_if_fail(cmd_fridaL_cd);

	RzCmdDesc *cmd_fridaC_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridaC", RZ_OUTPUT_MODE_JSON, rz_cmd_fridaC_handler, &cmd_fridaC_help);
	rz_warn_if_fail(cmd_fridaC_cd);

	RzCmdDesc *cmd_fridaN_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridaN", RZ_OUTPUT_MODE_JSON, rz_cmd_fridaN_handler, &cmd_fridaN_help);
	rz_warn_if_fail(cmd_fridaN_cd);

	RzCmdDesc *cmd_fridaRN_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridaRN", RZ_OUTPUT_MODE_JSON, rz_cmd_fridaRN_handler, &cmd_fridaRN_help);
	rz_warn_if_fail(cmd_fridaRN_cd);

	RzCmdDesc *cmd_fridaf_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridaf", RZ_OUTPUT_MODE_JSON, rz_cmd_fridaf_handler, &cmd_fridaf_help);
	rz_warn_if_fail(cmd_fridaf_cd);

	RzCmdDesc *cmd_fridaD_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridaD", RZ_OUTPUT_MODE_JSON, rz_cmd_fridaD_handler, &cmd_fridaD_help);
	rz_warn_if_fail(cmd_fridaD_cd);

	RzCmdDesc *cmd_fridaIm_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridaIm", RZ_OUTPUT_MODE_JSON, rz_cmd_fridaIm_handler, &cmd_fridaIm_help);
	rz_warn_if_fail(cmd_fridaIm_cd);
	rz_cmd_batch_end(core->rcmd);
}
